# Generated by Django 6.0.3 on 2026-03-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employerprofile',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
