# Generated by Django 6.0.3 on 2026-03-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='resume',
            name='title',
            field=models.CharField(default='My Resume', max_length=255),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(upload_to='resumes/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
