# Generated by Django 6.0.3 on 2026-03-20 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_initial'),
        ('jobs', '0003_alter_job_id_alter_jobskill_id'),
        ('saved_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedjob',
            options={'ordering': ['-saved_at']},
        ),
        migrations.RenameField(
            model_name='savedjob',
            old_name='created_at',
            new_name='saved_at',
        ),
        migrations.AddField(
            model_name='savedjob',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='savedjob',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to='candidates.candidateprofile'),
        ),
        migrations.AlterField(
            model_name='savedjob',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='savedjob',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='jobs.job'),
        ),
    ]
