# Generated by Django 4.2.28 on 2026-02-26 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employers', '0002_initial'),
        ('candidates', '0002_initial'),
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.candidateprofile'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employers.employerprofile'),
        ),
    ]
