# Generated by Django 4.2.28 on 2026-03-02 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_add_constraints_and_ordering'),
        ('messaging', '0002_initial'),
    ]

    operations = [
    ]
