export const SKILLS_OPTIONS = [
  "React", "Vue.js", "Angular", "TypeScript", "JavaScript",
  "Node.js", "Python", "Java", "Go", "Rust", "C++",
  "SQL", "PostgreSQL", "MongoDB", "Redis",
  "AWS", "GCP", "Azure", "Docker", "Kubernetes",
  "Machine Learning", "GraphQL", "Figma", "REST API"
];

export const EXPERIENCE_LEVELS = [
  { label: "Any", min: 0, max: 99 },
  { label: "Fresher (0–1 yr)", min: 0, max: 1 },
  { label: "Junior (1–3 yrs)", min: 1, max: 3 },
  { label: "Mid (3–5 yrs)", min: 3, max: 5 },
  { label: "Senior (5–8 yrs)", min: 5, max: 8 },
  { label: "Lead (8+ yrs)", min: 8, max: 99 },
];

export const EDUCATION_LEVELS = [
  "Any", "High School", "Associate's", "Bachelor's", "Master's", "PhD"
];

export const MOCK_CANDIDATES = [
  {
    id: 1,
    name: "Aanya Sharma",
    role: "Senior Frontend Developer",
    experienceYears: 5,
    education: "Bachelor's",
    skills: ["React", "TypeScript", "Node.js", "GraphQL", "AWS"],
    location: "Bangalore",
    email: "aanya.sharma@email.com",
    phone: "+91 98765 43210",
    summary: "Passionate frontend developer with 5 years of experience building scalable web applications. Strong expertise in React ecosystem and modern TypeScript patterns.",
    resumeFile: null,
    resumeUrl: null,
    shortlisted: false,
  },
  {
    id: 2,
    name: "Rohan Mehta",
    role: "Full Stack Engineer",
    experienceYears: 3,
    education: "Master's",
    skills: ["React", "Python", "AWS", "Docker", "MongoDB", "REST API"],
    location: "Mumbai",
    email: "rohan.mehta@email.com",
    phone: "+91 98123 45678",
    summary: "Full stack engineer experienced in building microservices and cloud-native applications. Proficient in both frontend and backend technologies.",
    resumeFile: null,
    resumeUrl: null,
    shortlisted: false,
  },
  {
    id: 3,
    name: "Priya Nair",
    role: "ML Engineer",
    experienceYears: 4,
    education: "Master's",
    skills: ["Python", "Machine Learning", "SQL", "AWS", "PostgreSQL"],
    location: "Hyderabad",
    email: "priya.nair@email.com",
    phone: "+91 90012 34567",
    summary: "ML engineer with focus on NLP and computer vision. Deployed 10+ production ML models serving millions of users.",
    resumeFile: null,
    resumeUrl: null,
    shortlisted: false,
  },
  {
    id: 4,
    name: "Karan Joshi",
    role: "Backend Developer",
    experienceYears: 2,
    education: "Bachelor's",
    skills: ["Java", "SQL", "Docker", "Redis", "REST API"],
    location: "Pune",
    email: "karan.joshi@email.com",
    phone: "+91 91234 56789",
    summary: "Backend developer specializing in Java Spring Boot microservices. Experience with high-throughput systems and database optimization.",
    resumeFile: null,
    resumeUrl: null,
    shortlisted: false,
  },
  {
    id: 5,
    name: "Meera Iyer",
    role: "DevOps Engineer",
    experienceYears: 6,
    education: "Bachelor's",
    skills: ["Kubernetes", "Docker", "AWS", "Go", "PostgreSQL", "Python"],
    location: "Chennai",
    email: "meera.iyer@email.com",
    phone: "+91 88765 43211",
    summary: "DevOps engineer with deep expertise in container orchestration and CI/CD pipelines. Reduced deployment time by 60% at previous company.",
    resumeFile: null,
    resumeUrl: null,
    shortlisted: false,
  },
  {
    id: 6,
    name: "Dev Patel",
    role: "Frontend Developer",
    experienceYears: 1,
    education: "Bachelor's",
    skills: ["React", "Vue.js", "TypeScript", "Figma", "JavaScript"],
    location: "Ahmedabad",
    email: "dev.patel@email.com",
    phone: "+91 77654 32109",
    summary: "Junior frontend developer with strong design sensibility. Built 5 production applications from scratch with pixel-perfect implementations.",
    resumeFile: null,
    resumeUrl: null,
    shortlisted: false,
  },
  {
    id: 7,
    name: "Sneha Reddy",
    role: "Data Engineer",
    experienceYears: 7,
    education: "Bachelor's",
    skills: ["Python", "SQL", "PostgreSQL", "AWS", "MongoDB", "Machine Learning"],
    location: "Hyderabad",
    email: "sneha.reddy@email.com",
    phone: "+91 99887 76655",
    summary: "Senior data engineer building robust ETL pipelines and data warehouses. Managed petabyte-scale data infrastructure.",
    resumeFile: null,
    resumeUrl: null,
    shortlisted: false,
  },
  {
    id: 8,
    name: "Arjun Singh",
    role: "Cloud Architect",
    experienceYears: 9,
    education: "Master's",
    skills: ["AWS", "GCP", "Azure", "Kubernetes", "Docker", "Go", "Python"],
    location: "Delhi",
    email: "arjun.singh@email.com",
    phone: "+91 98001 23456",
    summary: "Cloud architect with expertise across all major cloud platforms. Designed infrastructure for unicorn startups and Fortune 500 companies.",
    resumeFile: null,
    resumeUrl: null,
    shortlisted: false,
  },
];
